backbone:
  model_name: efficientnetv2_rw_m
  pretrained: True
  num_classes: 0
  in_chans: 3
fc_dropout: 0.5
output_dim: 1
loss:
  _target_: torch.nn.BCEWithLogitsLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 20
  eta_min: 1e-4
  