general:
  seed: 42
  num_workers: 2
  start_cv: 4
data:
  data_path: ${hydra:runtime.cwd}/data/train.csv
  n_splits: 5
  data_type: 'train'
datamodule:
  transform:
    image_size: 224
  dataloader:
    batch_size: 32
    num_workers: ${...general.num_workers}
model:
  backbone:
    model_name: swin_large_patch4_window7_224
    pretrained: True
    num_classes: 0
    in_chans: 3
  fc_dropout: 0.5
  output_dim: 1
  loss:
    _target_: torch.nn.BCEWithLogitsLoss
  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-6
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 20
    eta_min: 1e-4
  mixup: true
trainer:
  gpus: 1
  max_epochs: 50
wandb:
  name: swin_large_clean_crop
  project: petfinder
